# Generated by Django 5.1.2 on 2024-10-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.CharField(max_length=300, verbose_name='описание')),
                ('content', models.TextField(verbose_name='контент')),
                ('date', models.DateTimeField(verbose_name='дата публикации')),
                ('author', models.CharField(max_length=100, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
    ]
