# Generated by Django 4.2 on 2024-11-13 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_tag_alter_category_name_alter_news_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram ссылка')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook ссылка')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='whatsapp ссылка')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='telegram ссылка')),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='news.news', verbose_name='новость')),
            ],
            options={
                'verbose_name': 'ссылки новостя',
                'verbose_name_plural': 'ссылки новостей',
            },
        ),
    ]
