# Generated by Django 4.2 on 2024-11-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_is_published_news_views_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменении'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата публикации'),
        ),
    ]
